-- CREATION OF STRING TIME DURATIONS TO TIME VALUES TABLE

local BASE = 1/32

local BASIC_VALS = {
-- BASIC TIME VALUES
    ["4/4"]   = 64,    -- whole
    ["2/4"]   = 32,    -- half
    ["1/4"]   = 16,    -- quarter
    ["1/8"]   = 8,    -- eighth
    ["1/16"]  = 4,    -- sixteenth
    ["1/32"]  = 2,    -- thirty second
    ["1/64"]  = 1,    -- sixty fourth
}

-- Time Signature Bar Values

local TIMESIGS = {
    -- NON 4/4 SIMPLE TIME SIGS
    ["6/4"]  = 96,
    ["3/2"]  = 96,
    ["2/2"]  = 64,
    ["3/4"]  = 48, 
    -- COMPOUND TIME SIGS
    ["12/8"] = 96,
    ["9/8"]  = 72, 
    ["6/8"]  = 48,
    ["4/8"]  = 36, 
    ["3/8"]  = 24, 
    --IRREGULAR TIME SIGS
    ["10/4"] = 160,
    ["9/4"]  = 144,
    ["7/4"]  = 112, 
    ["6/4"]  = 96, 
    ["5/4"]  = 80, 
    ["7/8"]  = 56, 
    ["5/8"]  = 40, 
}

-- Use these as the header comments for each tuplet

local TUPLETS = {
    "Triplets",
    "Quadruplets",
    "Quintuplets",
    "Sextuplets",
    "Septuplets",
    "Octuplets",
    "Nonuplets",
}

-- Function Calls

local function Basic()
    local rets = {}
    for k,v in pairs(BASIC_VALS) do
        rets[k] = v * BASE
    end
    return rets
end

local function Dotteds() 
    local rets = {
        ["Single Dotted"] = {},
        ["Double Dotted"] = {},
    }
    for k,v in pairs(BASIC_VALS) do
        local basic_dot = v * BASE * 3/2
        rets["Single Dotted"][k.."*"] = basic_dot 
        rets["Double Dotted"][k.."**"] = basic_dot * 3/2 
        -- if you want triple dotteds you're wrong and you should feel bad
    end
    return rets
end

local function Tuplets()
    local rets = {}
    for i, tup_name in ipairs(TUPLETS) do
        local name = tup_name
        rets[name] = {}
        for k, v in pairs(BASIC_VALS) do
            --[[ `t` stands for "tuplet" here.
            `TUPLETS[i]` is triplet, so start val at 3 ]]
            local t_val = i + 2 
            local t_key = "["..t_val.."]"..k
            rets[name][t_key] = v * BASE * 2/t_val
        end
    end
    return rets
end

local function TimeSignatures()
    local rets = {}
    for k,v in pairs(TIMESIGS) do
        rets[k] = v * BASE
    end
    return rets
end

local rhythms = {
    -- Index-Value pairs so they can be arranged
    { ["Basic Values"] = Basic(), },
    { ["Time Signatures"] = TimeSignatures(), }, 
    Dotteds(), 
    Tuplets(),
}

--[[ This is not meant for you to use! 
This is for me, the mod maker, to generate the rhythms.lua file.
I'd rather have the hardcoded table readily available,
rather than constantly recreating it everytime the mod runs. 

Lua 5.1 or later must be installed. To run, open your terminal.
Make sure the working directory is the one where this file is found.

Run this command: lua .\make_pitches.lua

It should output to the same directory this file is located in. ]]

local file = io.open("rhythms.lua", "w")
file:write("--[[ Generated by make_rhythms.lua ]]\n\n")
file:write("local rhythms = {\n")

file:write("\n\t--[[ 0 TIME VALUE/CHORD ]]\n\n")
file:write("\t[\"0\"] = 0,\n")

for _, tbl in ipairs(rhythms) do
    for header, sub_tbl in pairs(tbl) do
        file:write("\n\t--[[ ", header, " ]]\n\n")
        for k, v in pairs(sub_tbl) do
            file:write("\t[\"", k, "\"] = ", v, ",\n")
        end
    end 
end

file:write("}\n\nreturn rhythms")
file:close()
